USE [master]
GO

/****** Object:  Database [InformationData]    Script Date: 2022/12/23 18:56:09 ******/
CREATE DATABASE [InformationData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InformationData', FILENAME = N'D:\黄油\informationdata\InformationData\InformationData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InformationData_log', FILENAME = N'D:\黄油\informationdata\InformationData\InformationData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InformationData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InformationData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InformationData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InformationData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InformationData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InformationData] SET ARITHABORT OFF 
GO

ALTER DATABASE [InformationData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InformationData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InformationData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InformationData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InformationData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InformationData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InformationData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InformationData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InformationData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InformationData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InformationData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InformationData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InformationData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InformationData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InformationData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InformationData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InformationData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InformationData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InformationData] SET  MULTI_USER 
GO

ALTER DATABASE [InformationData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InformationData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InformationData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InformationData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InformationData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InformationData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [InformationData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InformationData] SET  READ_WRITE 
GO

